//
//  This file was auto-generated by Macaw tools 0.9.5-Beta8 version built on Tue, 31 Oct 2017 00:05:58 +0530 
//
package io.macaw.demo.petstore.ordersservice.impl;

import java.lang.Override;
import java.util.Date;

import com.cfx.service.api.config.Configuration;

import io.macaw.db.mysql.utils.DbConnector;
import io.macaw.demo.petstore.ordersservice.DomainEntityInstantiator;
import io.macaw.demo.petstore.ordersservice.mysql.db.dao.LineitemDAO;
import io.macaw.demo.petstore.ordersservice.mysql.db.dao.OrderDAO;
import io.macaw.demo.petstore.ordersservice.mysql.db.dto.Lineitem;
import io.macaw.demo.petstore.ordersservice.mysql.db.dto.Order;

public class Ordersservice implements com.cfx.service.api.Service, io.macaw.demo.petstore.ordersservice.Ordersservice {
    private static final String MYSQL = "mysql";
    private Configuration config;
  @Override
  public void initialize(com.cfx.service.api.config.Configuration config) throws com.cfx.service.api.ServiceException {
  this.config = config;
  }

  @Override
  public void start(com.cfx.service.api.StartContext startContext) throws com.cfx.service.api.ServiceException {
  DbConnector.initialise();
  }

  @Override
  public void stop(com.cfx.service.api.StopContext stopContext) throws com.cfx.service.api.ServiceException {
  }

  @Override
  public io.macaw.demo.petstore.ordersservice.Order addOrder(io.macaw.demo.petstore.ordersservice.Order order) {
	  io.macaw.demo.petstore.ordersservice.Order ord = DomainEntityInstantiator.getInstance().newInstance(io.macaw.demo.petstore.ordersservice.Order.class);
	  // TODO : Add order to dto conversion in OrderDAO and replace these codes to simplification.
	  Order dto = new Order();
	  dto.setOrderid(order.getOrderid());
	  dto.setUserid(order.getUserid());
	  //dto.setOrderdate(order.getOrderdate()); //TODO: Change date type
	  dto.setShipaddr1(order.getShipaddr1());
	  dto.setShipaddr2(order.getShipaddr2());
	  dto.setShipcity(order.getShipcity());
	  dto.setShipstate(order.getShipstate());
	  dto.setShipzip(order.getShipzip());
	  dto.setShipcountry(order.getShipcountry());
	  dto.setBilladdr1(order.getBilladdr1());
	  dto.setBilladdr2(order.getBilladdr2());
	  dto.setBillstate(order.getBillstate());
	  dto.setBillzip(order.getBillzip());
	  dto.setBillcountry(order.getBillcountry());
	  dto.setCourier(order.getCourier());
	  dto.setTotalprice(order.getTotalprice());
	  dto.setShipdate(new Date());
	 // dto.setShipdate(order.gets);
	  dto.setBilltofirstname(order.getBilltofirstname());
	  dto.setBilltolastname(order.getBilltolastname());
	  dto.setShiptofirstname(order.getShiptofirstname());
	  dto.setShiptolastname(order.getShiptolastname());
	  dto.setCreditcard(order.getCreditcard());
	//  dto.setExpirydate(order.getExpirydate());
	  dto.setExpirydate(new Date());
	  dto.setCardtype(order.getCreditcard());
	  dto.setLocale(order.getLocale());
	  
	  try {
		  new OrderDAO().insert(dto);
	  }catch(Exception e) {
		  e.printStackTrace();
	  }
	  
    return order;
  }

  @Override
  public io.macaw.demo.petstore.ordersservice.Lineitem addLineitem(io.macaw.demo.petstore.ordersservice.Lineitem lineitem) {
	  
	  Lineitem dto = new Lineitem();
	  dto.setOrderid(lineitem.getOrderid());
	  dto.setLinenum(lineitem.getLinenum());
	  dto.setQuantity(lineitem.getQuantity());
	  dto.setUnitprice(lineitem.getUnitprice());
	  dto.setItemid(lineitem.getItemid());
	  
	  try {
		  new LineitemDAO().insert(dto);
	  }catch(Exception e) {
		  e.printStackTrace();
	  }
	  return lineitem;
  }

  @Override
  public io.macaw.demo.petstore.ordersservice.Lineitem updateLineitem(io.macaw.demo.petstore.ordersservice.Lineitem lineitem) {
	  Lineitem dto = new Lineitem();
	  dto.setOrderid(lineitem.getOrderid());
	  dto.setLinenum(lineitem.getLinenum());
	  dto.setQuantity(lineitem.getQuantity());
	  dto.setUnitprice(lineitem.getUnitprice());
	  dto.setItemid(lineitem.getItemid());
	  
	  try {
		  new LineitemDAO().update(dto);
	  }catch(Exception e) {
		  e.printStackTrace();
	  }
	  return lineitem;
  }

  @Override
  public String deleteLineitem(String lineitemid) {
    try {
    	new LineitemDAO().deleteById(lineitemid);
    }catch(Exception e)
    {
    	e.printStackTrace();
    }
    return null;
  }

  @Override
  public java.util.List<io.macaw.demo.petstore.ordersservice.Lineitem> getLineitemsByOrderid(String orderid) {
    Lineitem lineit = new LineitemDAO().findById(orderid);
    io.macaw.demo.petstore.ordersservice.Lineitem lt = DomainEntityInstantiator.getInstance().newInstance(io.macaw.demo.petstore.ordersservice.Lineitem.class);
    lt.setItemid(lineit.getItemid());
    lt.setLinenum(lineit.getLinenum());
    lt.setOrderid(lineit.getOrderid());
    lt.setQuantity(lineit.getQuantity());
    lt.setUnitprice(lineit.getUnitprice());
    
    return null;
  }

  @Override
  public io.macaw.demo.petstore.ordersservice.Order updateOrder(io.macaw.demo.petstore.ordersservice.Order order) {
	  Order dto = new Order();
	  dto.setOrderid(order.getOrderid());
	  dto.setUserid(order.getUserid());
	  dto.setOrderdate(new Date()); //TODO: Change date type
	  dto.setShipaddr1(order.getShipaddr1());
	  dto.setShipaddr2(order.getShipaddr2());
	  dto.setShipcity(order.getShipcity());
	  dto.setShipstate(order.getShipstate());
	  dto.setShipzip(order.getShipzip());
	  dto.setShipcountry(order.getShipcountry());
	  dto.setBilladdr1(order.getBilladdr1());
	  dto.setBilladdr2(order.getBilladdr2());
	  dto.setBillstate(order.getBillstate());
	  dto.setBillzip(order.getBillzip());
	  dto.setBillcountry(order.getBillcountry());
	  dto.setCourier(order.getCourier());
	  dto.setTotalprice(order.getTotalprice());
	  // dto.setShipdate(order.gets); // field missing
	  dto.setShipdate(new Date());
	  dto.setBilltofirstname(order.getBilltofirstname());
	  dto.setBilltolastname(order.getBilltolastname());
	  dto.setShiptofirstname(order.getShiptofirstname());
	  dto.setShiptolastname(order.getShiptolastname());
	  dto.setCreditcard(order.getCreditcard());
	  dto.setOrderdate(new Date(order.getOrderdate()));
	  dto.setExpirydate(new Date(order.getExpirydate()));
	  dto.setCardtype(order.getCreditcard());
	  dto.setLocale(order.getLocale());
	  
	  try {
		  new OrderDAO().update(dto);
	  }catch(Exception e) {
		  e.printStackTrace();
	  }
	  
    return order;
  }

  @Override
  public String deleteOrder(String orderid) {
    try {
    	new OrderDAO().deleteById(orderid);
    }catch(Exception e) {
    	e.printStackTrace();
    }
    return null;
  }

  @Override
  public java.util.List<io.macaw.demo.petstore.ordersservice.Order> getAllOrdersByUserid(String userid) {
	  return (new OrderDAO().getOrdersByUser(userid));
  }

  @Override
  public io.macaw.demo.petstore.ordersservice.Order getOrderByOrderid(String orderid) {
	  Order order = new OrderDAO().findById(orderid);
	  return (new OrderDAO().getEntityFromDTO(order));
  }
}
