use productmysql;


DROP TABLE IF EXISTS CATEGORY CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS ITEM CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS PRODUCT CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS SUPPLIER CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;

commit;


