use usersmysql;


DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS BANNERDATA CASCADE;
DROP TABLE IF EXISTS bannerdata CASCADE;
DROP TABLE IF EXISTS CREDENTIALS CASCADE;
DROP TABLE IF EXISTS credentials CASCADE;
DROP TABLE IF EXISTS PROFILE CASCADE;
DROP TABLE IF EXISTS profile CASCADE;

commit;


